baseURL = "https://golangnepal.github.io/"
languageCode = "en-us"
title = "Golang Nepal"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "Community"
    githubUsername = "#"
    accent = "lightblue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/events/"
    name = "Events"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/GolangNepal/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/GolangNepal/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.meetup.com/Golang-Kathmandu/"
    name = "meetup"
    weight = 3

